modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = ""
license = "MIT License"

[[mods]]
modId = "thief_tweaks"
version = "${file.jarVersion}"
logoFile = "logo.png"
itemIcon = "minecraft:dirt"
configBackground = "minecraft:textures/block/dirt.png"
authors = "DavigJ"
credits = ""
displayURL = ""
displayName = "Thief's Tweaks"
description = '''
    A mod that adds a couple tweaks to the Thief's Hood from Environmental.
    '''

[[dependencies.thief_tweaks]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.19.3)"
ordering = "NONE"
side = "BOTH"

[[dependencies.thief_tweaks]]
modId = "forge"
mandatory = true
versionRange = "[43.3.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.thief_tweaks]]
modId = "blueprint"
mandatory = true
versionRange = "[6.2.0,)"
ordering = "AFTER"
side = "BOTH"